
export const colorThemes = {
  green: {
    name: 'グリーン',
    primary: 'emerald',
    primaryHover: 'emerald-700',
    primaryBg: 'from-emerald-600 to-emerald-700',
    primaryBgHover: 'from-emerald-700 to-emerald-800',
    accent: 'emerald-600',
    accentHover: 'emerald-700',
    accentBg: 'emerald-50',
    accentBorder: 'emerald-600',
    accentText: 'emerald-700',
  },
  gold: {
    name: 'ゴールド',
    primary: 'gold',
    primaryHover: 'gold-700',
    primaryBg: 'bg-gold-luxury',
    primaryBgHover: 'bg-gold-premium',
    accent: 'gold-500',
    accentHover: 'gold-600',
    accentBg: 'gold-50',
    accentBorder: 'gold-500',
    accentText: 'gold-600',
  },
  colorful: {
    name: 'カラフル',
    primary: 'mste-electric-cyan',
    primaryHover: 'mste-royal-blue',
    primaryBg: 'bg-mste-gradient',
    primaryBgHover: 'bg-mste-aurora',
    accent: 'mste-electric-cyan',
    accentHover: 'mste-hot-magenta',
    accentBg: 'mste-highlight',
    accentBorder: 'mste-electric-cyan',
    accentText: 'mste-electric-cyan',
  },
  'colorful-light': {
    name: 'カラフル（ライト）',
    primary: 'mste-electric-cyan',
    primaryHover: 'mste-royal-blue',
    primaryBg: 'bg-mste-gradient',
    primaryBgHover: 'bg-mste-aurora',
    accent: 'mste-electric-cyan',
    accentHover: 'mste-hot-magenta',
    accentBg: 'mste-highlight',
    accentBorder: 'mste-electric-cyan',
    accentText: 'mste-electric-cyan',
  },
};
